# Add in Home Assitant Automation UI. Handles doorbell press notifications.
alias: Kitchen doorbell press notifications
description: ""
trigger:
  - type: motion
    platform: device
    device_id: {BELL_ENTITY_ID}
    entity_id: binary_sensor.{BELL_ENTITY_NAME}
    domain: binary_sensor
condition: []
action:
  - service: notify.{NOTIFCATION_GROUP_NAME}
    data_template:
      message: {BELL_NAME} Bell is ringing
      data:
        image: https://{FRIGATE HOST}/frigate/api/front-door/latest.jpg?h=600
        tag: "{{trigger[\"id\"]}}"
        when: "{{trigger[\"to_state\"][\"last_changed\"]}}"
mode: single
