# Add in Home Assitant Automation UI. Handles all detection notifications for all cameras in Frigate.

alias: Frigate mobile notifications
description: ""
trigger:
  - platform: mqtt
    topic: frigate/events
    payload: new
    value_template: "{{ value_json.type }}"
condition: []
action:
  - service: notify.{NOTIFICATION_GROUP_NAME}
    data_template:
      message: >-
        A {{trigger.payload_json["after"]["label"]}} was detected on
        {{trigger.payload_json["after"]["camera"]}}
      data:
        image: >-
          https://<PUBLIC_HA_HOST>/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg
        tag: "{{trigger.payload_json[\"after\"][\"id\"]}}"
        when: "{{trigger.payload_json[\"after\"][\"start_time\"]|int}}"
        entity_id: camera.{{trigger.payload_json["after"]["camera"]|replace('-', '_')}}
mode: single
