alias: Re-enable Frigate Notifications
description: ""
trigger:
  - platform: time
    at: "21:00:00"
  - platform: time
    at: "23:59:00"
  - platform: time
    at: "03:00:00"
  - platform: time
    at: "09:00:00"
  - platform: time
    at: "13:00:00"
  - platform: time
    at: "16:00:00"
condition: []
action:
  - service: automation.turn_on
    data: {}
    target:
      entity_id: automation.front_door_person_notification_2
mode: single
