x-health-check-defaults: &health_check_defaults
  interval: 30s
  timeout: 10s
  retries: 5
  start_period: 60s

services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /nvr-media/frigate:/media/frigate
      - ./config:/config
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
#    ports:
#      - 5000:5000
    environment:
      - FRIGATE_CAM_DOMAIN
      - FRIGATE_RTSP_USER
      - FRIGATE_RTSP_PASSWORD
      - FRIGATE_MQTT_USER
      - FRIGATE_MQTT_PASSWORD
    depends_on:
      - mqtt
    logging:
      driver: none
    extra_hosts:
      - "cam.garden.coia.io:192.168.3.179"
      - "cam-exterior.workshop.coia.io:192.168.3.9"
      - "cam-exterior.garage.coia.io:192.168.3.7"
      - "cam.entrance.coia.io:192.168.3.87"
    healthcheck:
      <<: *health_check_defaults
      test: [ "CMD", "wget", "--spider", "http://localhost:5000/" ]
    labels:
      autoheal-app: true

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2
    restart: unless-stopped
    init: true
    ports:
      - 1883:1883
    environment:
      - FRIGATE_MQTT_USER
      - FRIGATE_MQTT_PASSWORD
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/mosquitto.passwd:/mosquitto/mosquitto.passwd:ro
    healthcheck:
      <<: *health_check_defaults
      test: [ "CMD", "timeout", "1", "mosquitto_sub", "-h", "localhost", "-p", "1883", "-t", "'topic'", "-u", "${FRIGATE_MQTT_USER}", "-P", "${FRIGATE_MQTT_PASSWORD}", "-E", "-i", "probe" ]
    logging:
      driver: none
    labels:
      autoheal-app: true

  scrypted:
    image: ghcr.io/koush/scrypted
    container_name: scrypted
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - ./scrypted:/server/volume
    logging:
      driver: none
    healthcheck:
      <<: *health_check_defaults
      test: ["CMD", "curl", "-f", "-k", "-L", "http://127.0.0.1:11080/endpoint/@scrypted/core/public/#/"]
    labels:
      autoheal-app: true

  frigate-home-proxy:
    image: ghcr.io/gitgc/home-proxy-webserver:main
    container_name: frigate-home-proxy
    restart: unless-stopped
    init: true
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_DNS_EMAIL
      - CADDY_DOMAIN
      - DO_AUTH_TOKEN
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"
      - "./home-proxy-webserver/site/:/var/www/html/"
      - "./home-proxy-webserver/caddy_data/:/data/"
      - "./home-proxy-webserver/caddy_config/:/config/"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "nvr.coia.io:192.168.1.86"
    depends_on:
      - frigate
    logging:
      driver: none
    healthcheck:
      <<: *health_check_defaults
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "https://nvr.coia.io/caddy-health-check" ]
    labels:
      autoheal-app: true

  autoheal:
    image: willfarrell/autoheal:latest
    network_mode: none
    restart: unless-stopped
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal-app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
