services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.16.0
    shm_size: "512mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /nvr-media/frigate:/media/frigate
      - ./config:/config
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
#    ports:
#      - 8971:8971
#      - 5000:5000
#      - 8554:8554
#      - 8555:8555/tcp
#      - 8555:8555/udp
    environment:
      - FRIGATE_CAM_DOMAIN
      - FRIGATE_RTSP_USER
      - FRIGATE_RTSP_PASSWORD
    depends_on:
      - mqtt
#    logging:
#      driver: none
    extra_hosts:
      - "cam.garden.coia.io:192.168.3.179"
      - "cam-exterior.workshop.coia.io:192.168.3.9"
      - "cam-exterior.garage.coia.io:192.168.3.7"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:5000/" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:1.6
    init: true
#    ports:
#      - 1883:1883
    healthcheck:
      test: [ "CMD", "timeout", "1", "mosquitto_sub", "-h", "localhost", "-p", "1883", "-t", "'topic'", "-E", "-i", "probe" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    logging:
      driver: none

  scrypted:
    image: ghcr.io/koush/scrypted
    container_name: scrypted
    restart: unless-stopped
    network_mode: host
#    environment:
#      - SCRYPTED_DOCKER_AVAHI=true
    devices:
#      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128
#    security_opt:
#      - apparmor:unconfined
    volumes:
      - ./scrypted:/server/volume
#      - /var/run/dbus:/var/run/dbus
#      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    logging:
      driver: none

  frigate-home-proxy:
    image: ghcr.io/gitgc/home-proxy-webserver:main
    container_name: frigate-home-proxy
    restart: unless-stopped
    init: true
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_DNS_EMAIL
      - CADDY_DOMAIN
      - DO_AUTH_TOKEN
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"
      - "./home-proxy-webserver/site/:/var/www/html/"
      - "./home-proxy-webserver/caddy_data/:/data/"
      - "./home-proxy-webserver/caddy_config/:/config/"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    #healthcheck:
    #  test: [ "CMD", "wget", "--spider", "https://nvr.${CADDY_DOMAIN}/caddy-health-check" ]
    #  interval: 30s
    #  timeout: 10s
    #  retries: 5
    #  start_period: 60s
    depends_on:
      - frigate
    logging:
      driver: none

#  watchtower:
#    container_name: watchtower
#    image: containrrr/watchtower
#    restart: unless-stopped
#    environment:
#      - WATCHTOWER_SCHEDULE
#      - WATCHTOWER_CLEANUP=true
#      - WATCHTOWER_ROLLING_RESTART=true
#      - WATCHTOWER_INCLUDE_STOPPED=true
#      - WATCHTOWER_REVIVE_STOPPED=true
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /etc/localtime:/etc/localtime:ro
