mqtt:
  host: mqtt

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  workshop-yard:
    ffmpeg:
      hwaccel_args: &defaultHardwareAccelArgs
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.223:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - rtmp
            - record
            - detect
    rtmp: &defaultRTMPArgs
      enabled: True
    detect: &defaultDectectArgs
      width: 1280
      height: 1024
      fps: 5
    objects: &objectsCarAndPerson
      track:
        - person
        - car
    record:
      enabled: True
      retain:
        mode: motion
        days: 7
      events:
        required_zones:
          - yard
        retain:
          default: 14
          mode: motion
    snapshots: &defaultSnapshotArgs
      timestamp: True
      bounding_box: True
      crop: True
      enabled: True
    motion:
      mask:
        - 0,0,366,0,439,139,418,233,312,310,295,520,0,592
    zones:
      yard:
        coordinates: 1280,1024,0,1024,0,0,930,0,1126,354,1280,381

  garage-yard:
    ffmpeg:
      hwaccel_args: *defaultHardwareAccelArgs
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.168:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - rtmp
            - record
            - detect
    rtmp: *defaultRTMPArgs
    detect: *defaultDectectArgs
    objects: *objectsCarAndPerson
    record:
      retain:
        mode: motion
        days: 7
      events:
        required_zones:
          - yard
        retain:
          default: 14
          mode: motion    
    snapshots: *defaultSnapshotArgs
    zones:
      parking_bay:
        coordinates: 252,873,154,738,140,477,183,289,481,217,657,304,892,484,940,823
      yard:
        coordinates: 1280,0,0,0,0,229,621,170,698,299,857,348,946,459,946,1024,1280,1024

  front-door:
    ffmpeg:
      hwaccel_args: *defaultHardwareAccelArgs
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.148:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - rtmp
            - record
            - detect
    rtmp: *defaultRTMPArgs
    detect: *defaultDectectArgs
    objects:
      track:
        - person
    record:
      enabled: True
      retain:
        mode: motion
        days: 7
      events:
        required_zones:
          - porch
        retain:
          default: 14
          mode: motion    
    snapshots: *defaultSnapshotArgs
    zones:
      porch:
        coordinates: 1280,1024,0,1024,0,0,1280,0,1280,423,526,392,524,577,546,754,778,778,1012,594,1155,592,1280,595
