tls:
  enabled: false

mqtt:
  host: mqtt

detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1

birdseye:
  enabled: false

cameras:
  workshop-yard:
    enabled: true
    ffmpeg:
      hwaccel_args: &defaultHardwareAccelArgs
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@cam-exterior.workshop.{FRIGATE_CAM_DOMAIN}:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles: &defaultExteriorRoles
            - record
            - detect
    detect: &defaultDetectArgs
      width: 1920
      height: 1080
      fps: 10
    objects:
      track:
        - person
        - car
        - dog
      filters:
        car: {}
    record:
      enabled: true
      retain: &defaultExteriorRetain
        mode: motion
        days: 14
    snapshots: &defaultSnapshotArgs
      timestamp: true
      bounding_box: true
      crop: true
      enabled: true
    motion:
      mask:
        - 0,0,505,0,526,98,281,93,418,233,312,310,295,520,0,592
    zones:
      yard:
        coordinates: 1920,1080,0,1080,0,0,930,0,1679,0,1624,217,1920,298
#    review:
#      alerts:
#        required_zones:
#          - yard

  garage-yard:
    ffmpeg:
      hwaccel_args: *defaultHardwareAccelArgs
      inputs:
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@cam-exterior.garage.{FRIGATE_CAM_DOMAIN}:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles: *defaultExteriorRoles
    detect: *defaultDetectArgs
    objects:
      track:
        - person
        - car
      filters:
        car:
          mask:
            - 0.778,0.423,0.679,0.356,0.657,0.283,0.692,0.182,0.736,0.187,0.899,0.202,0.98,0.29,0.96,0.482
            - 0.432,0.135,0.421,0.185,0.498,0.189,0.51,0.153
    record:
      enabled: true
      retain: *defaultExteriorRetain
    snapshots: *defaultSnapshotArgs

  garden:
    ffmpeg:
      hwaccel_args: *defaultHardwareAccelArgs
      inputs:
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@cam.garden.{FRIGATE_CAM_DOMAIN}:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles: *defaultExteriorRoles
    detect: *defaultDetectArgs
    objects:
      track:
        - person
        - dog
    record:
      enabled: true
      retain: *defaultExteriorRetain
    snapshots: *defaultSnapshotArgs
version: 0.14
