mqtt:
  host: mqtt

detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1

birdseye:
  enabled: False

cameras:
  workshop-yard:
    ffmpeg:
      hwaccel_args: &defaultHardwareAccelArgs
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@cam-exterior.workshop.{FRIGATE_CAM_DOMAIN}:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles: &defaultExteriorRoles
            - rtmp
            - record
            - detect
    rtmp: &defaultRTMPArgs
      enabled: True
    detect: &defaultDetectArgs
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
      filters:
        car:
          mask:
            - 1886,145,1787,64,1629,64,1605,213,1920,296
            - 1337,93,1401,0,965,0,1133,57,1217,68,1276,86
    record:
      enabled: True
      retain: &defaultExteriorRetain
        mode: motion
        days: 14
      events:
        required_zones:
          - yard
    snapshots: &defaultSnapshotArgs
      timestamp: True
      bounding_box: True
      crop: True
      enabled: True
    motion:
      mask:
        - 0,0,505,0,526,98,281,93,418,233,312,310,295,520,0,592
    zones:
      yard:
        coordinates: 1920,1080,0,1080,0,0,930,0,1679,0,1624,217,1920,298

  garage-yard:
    ffmpeg:
      hwaccel_args: *defaultHardwareAccelArgs
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@cam-exterior.garage.{FRIGATE_CAM_DOMAIN}:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles: *defaultExteriorRoles
    rtmp: *defaultRTMPArgs
    detect: *defaultDetectArgs
    objects:
      track:
        - person
        - car
      filters:
        car:
          mask:
            - 1493,457,1304,384,1262,306,1328,197,1413,202,1726,218,1881,313,1844,521
            - 1877,1080,1920,672,1311,479,931,369,803,315,467,343,518,357,121,358,200,836,551,1080
    record:
      enabled: True
      retain: *defaultExteriorRetain
    snapshots: *defaultSnapshotArgs

  garden:
    ffmpeg:
      hwaccel_args: *defaultHardwareAccelArgs
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@cam.garden.{FRIGATE_CAM_DOMAIN}:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles: *defaultExteriorRoles
    rtmp: *defaultRTMPArgs
    detect: *defaultDetectArgs
    objects:
      track:
        - person
        - dog
    record:
      enabled: True
      retain: *defaultExteriorRetain
    snapshots: *defaultSnapshotArgs

  front-door:
    ffmpeg:
      hwaccel_args: *defaultHardwareAccelArgs
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@cam.porch.{FRIGATE_CAM_DOMAIN}:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles: *defaultExteriorRoles
    rtmp: *defaultRTMPArgs
    detect: *defaultDetectArgs
    objects:
      track:
        - person
      filters:
        car:
          mask:
            - 805,406,1644,432,1533,892,1139,878,1139,1080,1541,1080,1920,1080,1920,428,1920,0,0,0,0,1080,1146,1080,1241,892,815,811
    record:
      enabled: True
      retain: *defaultExteriorRetain
    snapshots: *defaultSnapshotArgs
