version: 0.17-0

tls:
  enabled: false

mqtt:
  host: mqtt
  port: 1883
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

detectors:
  coral:
    type: edgetpu
    device: usb
  coral2:
    type: edgetpu
    device: usb:1

record:
  enabled: true
  continuous:
    days: 0
  motion:
    days: 14

detect:
  enabled: true
  width: 1920
  height: 1080
  fps: 10

snapshots:
  timestamp: true
  bounding_box: true
  crop: true
  enabled: true

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

model:
  path: plus://be9c11b486ba0e2b8ea13338d4cc66ee

birdseye:
  enabled: true
  mode: continuous
  width: 1920
  height: 1080
  layout:
    max_cameras: 4

objects:
  track:
      - face
      - person
  filters:
    face:
      min_score: 0.5
      threshold: 0.6

semantic_search:
  enabled: false
  model_size: small

face_recognition:
  enabled: true
  model_size: large
  min_area: 400

lpr:
  enabled: false
  model_size: small

classification:
  bird:
    enabled: false
  custom: {}

camera_groups:
  Birdseye:
    order: 1
    icon: LuBird
    cameras: birdseye

go2rtc:
  streams:
    workshop-yard:
      #- rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@cam-exterior.workshop.{FRIGATE_CAM_DOMAIN}:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
      - rtsp://host.docker.internal:33931/6413503b246a4c8a
    entrance:
      #- rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@cam.entrance.{FRIGATE_CAM_DOMAIN}:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
      - rtsp://host.docker.internal:35953/b545d5b512999cd0
    garage-yard:
      #- rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@cam-exterior.garage.{FRIGATE_CAM_DOMAIN}:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
      - rtsp://host.docker.internal:39481/bb6bc04b1f5f823c
    garden:
      #- rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@cam.garden.{FRIGATE_CAM_DOMAIN}:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
      - rtsp://host.docker.internal:34593/edf8fc8483d412f2
  webrtc:
    candidates:
      - 192.168.1.86:8555
      - stun:8555

cameras:
  workshop-yard:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/workshop-yard
          roles: &defaultExteriorRoles
            - record
            - detect
    objects:
      track:
        - face
        - person
        - car
        - bicycle
        - bear
        - deer
        - dog
        - cat
      filters:
        car: {}
    motion:
      threshold: 45
      contour_area: 45
      improve_contrast: true
      mask:
        - 0.086,0.643,0.17,0.618,0.344,0.568,0.474,0.628,0.637,0.774,0.522,1,0.201,1,0.067,1,0.045,0.807
        - 0.214,0.037,0.214,0,0,0,0.002,0.037
    zones:
      yard:
        coordinates: 1920,1080,0,1080,0,0,930,0,1679,0,1624,217,1920,298

  entrance:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/entrance
          roles: *defaultExteriorRoles
    objects:
      track:
        - face
        - person
        - package
        - dog
        - cat
        - bicycle
      filters:
        car: {}
        person:
          mask: 0.474,0.007,0.56,0.006,0.554,0.038,0.475,0.037
    motion:
      threshold: 40
      contour_area: 30
      improve_contrast: true
      mask: 0.812,0.041,0.964,0.038,0.964,0.075,0.812,0.078
    zones:
      yard:
        coordinates: 
          0.465,0.158,0.474,0.198,0.61,0.271,0.573,0.388,0.723,0.494,0.721,0.401,0.934,0.233,0.946,0.123,0.687,0.022,0.449,0.034
        loitering_time: 0
        inertia: 3
      porch:
        coordinates: 
          0.437,0.006,0.492,0.357,0.867,0.593,0.997,0.739,0.999,0.996,0.005,0.999,0,0.006
        loitering_time: 0
        inertia: 3

  garage-yard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage-yard
          roles: *defaultExteriorRoles
    objects:
      track:
        - face
        - person
        - car
        - bicycle
        - bear
        - deer
        - dog
        - cat
      filters:
        car:
          mask: 0.534,0,0.544,0.028,0.711,0.037,0.724,0.003
    motion:
      threshold: 45
      contour_area: 45
      improve_contrast: true
      mask: 0.754,0.046,0.965,0.041,0.965,0.078,0.754,0.078
    zones:
      yard:
        coordinates: 
          0,0.146,0.075,0.024,0.513,0.007,0.735,0.019,0.748,0.094,0.838,0.114,0.611,0.973,0.245,0.96,0.152,0.687,0,0.538
        loitering_time: 0

  garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden
          roles: *defaultExteriorRoles
    objects:
      track:
        - face
        - person
        - bicycle
        - bear
        - deer
        - dog
        - cat
      filters:
        person:
          mask: 
            0.2,0.167,0.223,0.162,0.226,0.246,0.228,0.288,0.203,0.289,0.199,0.242,0.196,0.193
    motion:
      mask:
        - 0.857,0.644,0.762,0.404,0.708,0.316,0.608,0.293,0.553,0.299,0.493,0.416,0.47,0.536,0.455,0.628,0.119,1,0.72,1
        - 0,0,0,0.161,0.128,0.13,0.218,0.1,0.272,0.094,0.314,0.083,0.333,0.059,0.492,0.044,0.586,0.062,0.736,0.099,0.884,0.14,1,0.152,1,0,0.722,0,0.36,0
      threshold: 45
      contour_area: 45
      improve_contrast: true
    zones:
      back-door:
        coordinates: 0.67,0.087,0.796,0.128,0.771,0.323,0.645,0.277
        loitering_time: 0
      raised-beds:
        coordinates: 0.404,0.357,0,0.58,0.001,0.258,0.212,0.168
        loitering_time: 0
      back-yard:
        coordinates: 
          0.002,0.996,0.121,0.999,1,1,0.998,0.155,0.336,0.059,0.002,0.161
        loitering_time: 0
